#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [git diff --name-only --cached | grep 'resume.json' -eq true];
    then
        npm run build:resume
        cd $(git rev-parse --show-toplevel)
        git add .
else
    echo "Resume not changed"
fi